[package]
name = "aoc-2015"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
itertools = "0.14.0"
md5 = "0.8.0"
once_cell = "1.21.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
thiserror = "2.0.17"
